//namespace Flux.Text
//{
//	public ref struct RuneSequences
//	{
//		/// <summary>The base62 encoding scheme uses 62 characters. The characters consist of the capital letters A-Z, the lower case letters a-z and the numbers 0–9.</summary>
//		/// <see cref="https://en.wikipedia.org/wiki/Base62"/>
//		public static System.ReadOnlySpan<System.Text.Rune> Base62
//			=> new System.Text.Rune[] { (System.Text.Rune)'0', (System.Text.Rune)'1', (System.Text.Rune)'2', (System.Text.Rune)'3', (System.Text.Rune)'4', (System.Text.Rune)'5', (System.Text.Rune)'6', (System.Text.Rune)'7', (System.Text.Rune)'8', (System.Text.Rune)'9', (System.Text.Rune)'A', (System.Text.Rune)'B', (System.Text.Rune)'C', (System.Text.Rune)'D', (System.Text.Rune)'E', (System.Text.Rune)'F', (System.Text.Rune)'G', (System.Text.Rune)'H', (System.Text.Rune)'I', (System.Text.Rune)'J', (System.Text.Rune)'K', (System.Text.Rune)'L', (System.Text.Rune)'M', (System.Text.Rune)'N', (System.Text.Rune)'O', (System.Text.Rune)'P', (System.Text.Rune)'Q', (System.Text.Rune)'R', (System.Text.Rune)'S', (System.Text.Rune)'T', (System.Text.Rune)'U', (System.Text.Rune)'V', (System.Text.Rune)'W', (System.Text.Rune)'X', (System.Text.Rune)'Y', (System.Text.Rune)'Z', (System.Text.Rune)'a', (System.Text.Rune)'b', (System.Text.Rune)'c', (System.Text.Rune)'d', (System.Text.Rune)'e', (System.Text.Rune)'f', (System.Text.Rune)'g', (System.Text.Rune)'h', (System.Text.Rune)'i', (System.Text.Rune)'j', (System.Text.Rune)'k', (System.Text.Rune)'l', (System.Text.Rune)'m', (System.Text.Rune)'n', (System.Text.Rune)'o', (System.Text.Rune)'p', (System.Text.Rune)'q', (System.Text.Rune)'r', (System.Text.Rune)'s', (System.Text.Rune)'t', (System.Text.Rune)'u', (System.Text.Rune)'v', (System.Text.Rune)'w', (System.Text.Rune)'x', (System.Text.Rune)'y', (System.Text.Rune)'z' };

//		/// <summary>https://en.wikipedia.org/wiki/Base64</summary>
//		public static System.ReadOnlySpan<System.Text.Rune> Base64
//			=> new System.Text.Rune[] { (System.Text.Rune)'A', (System.Text.Rune)'B', (System.Text.Rune)'C', (System.Text.Rune)'D', (System.Text.Rune)'E', (System.Text.Rune)'F', (System.Text.Rune)'G', (System.Text.Rune)'H', (System.Text.Rune)'I', (System.Text.Rune)'J', (System.Text.Rune)'K', (System.Text.Rune)'L', (System.Text.Rune)'M', (System.Text.Rune)'N', (System.Text.Rune)'O', (System.Text.Rune)'P', (System.Text.Rune)'Q', (System.Text.Rune)'R', (System.Text.Rune)'S', (System.Text.Rune)'T', (System.Text.Rune)'U', (System.Text.Rune)'V', (System.Text.Rune)'W', (System.Text.Rune)'X', (System.Text.Rune)'Y', (System.Text.Rune)'Z', (System.Text.Rune)'a', (System.Text.Rune)'b', (System.Text.Rune)'c', (System.Text.Rune)'d', (System.Text.Rune)'e', (System.Text.Rune)'f', (System.Text.Rune)'g', (System.Text.Rune)'h', (System.Text.Rune)'i', (System.Text.Rune)'j', (System.Text.Rune)'k', (System.Text.Rune)'l', (System.Text.Rune)'m', (System.Text.Rune)'n', (System.Text.Rune)'o', (System.Text.Rune)'p', (System.Text.Rune)'q', (System.Text.Rune)'r', (System.Text.Rune)'s', (System.Text.Rune)'t', (System.Text.Rune)'u', (System.Text.Rune)'v', (System.Text.Rune)'w', (System.Text.Rune)'x', (System.Text.Rune)'y', (System.Text.Rune)'z', (System.Text.Rune)'0', (System.Text.Rune)'1', (System.Text.Rune)'2', (System.Text.Rune)'3', (System.Text.Rune)'4', (System.Text.Rune)'5', (System.Text.Rune)'6', (System.Text.Rune)'7', (System.Text.Rune)'8', (System.Text.Rune)'9', (System.Text.Rune)'+', (System.Text.Rune)'/' };

//		/// <summary>Decimal unicode subscript</summary>
//		/// <see cref="https://en.wikipedia.org/wiki/Subscript_and_superscript"/>
//		/// <seealso cref="https://en.wikipedia.org/wiki/Decimal"/>
//		public static System.ReadOnlySpan<System.Text.Rune> DecimalSubscript
//			=> new System.Text.Rune[] { (System.Text.Rune)'\u2080', (System.Text.Rune)'\u2081', (System.Text.Rune)'\u2082', (System.Text.Rune)'\u2083', (System.Text.Rune)'\u2084', (System.Text.Rune)'\u2085', (System.Text.Rune)'\u2086', (System.Text.Rune)'\u2087', (System.Text.Rune)'\u2088', (System.Text.Rune)'\u2089' };
//		/// <summary>Decimal unicode superscript</summary>
//		/// <see cref="https://en.wikipedia.org/wiki/Subscript_and_superscript"/>
//		/// <seealso cref="https://en.wikipedia.org/wiki/Decimal"/>
//		public static System.ReadOnlySpan<System.Text.Rune> DecimalSuperscript
//			=> new System.Text.Rune[] { (System.Text.Rune)'\u2070', (System.Text.Rune)'\u00B9', (System.Text.Rune)'\u00B2', (System.Text.Rune)'\u00B3', (System.Text.Rune)'\u2074', (System.Text.Rune)'\u2075', (System.Text.Rune)'\u2076', (System.Text.Rune)'\u2077', (System.Text.Rune)'\u2078', (System.Text.Rune)'\u2079' };

//		/// <summary>The Mayan numeral system was the system to represent numbers and calendar dates in the Maya civilization. It was a vigesimal (base-20) positional numeral system.</summary>
//		/// <see cref="https://en.wikipedia.org/wiki/Maya_numerals"/>
//		/// <seealso cref="https://en.wikipedia.org/wiki/Vigesimal"/>
//		public static System.ReadOnlySpan<System.Text.Rune> MayanNumerals
//			=> new System.Text.Rune[] { System.Text.Rune.GetRuneAt("\U0001D2E0", 0), System.Text.Rune.GetRuneAt("\U0001D2E1", 0), System.Text.Rune.GetRuneAt("\U0001D2E2", 0), System.Text.Rune.GetRuneAt("\U0001D2E3", 0), System.Text.Rune.GetRuneAt("\U0001D2E4", 0), System.Text.Rune.GetRuneAt("\U0001D2E5", 0), System.Text.Rune.GetRuneAt("\U0001D2E6", 0), System.Text.Rune.GetRuneAt("\U0001D2E7", 0), System.Text.Rune.GetRuneAt("\U0001D2E8", 0), System.Text.Rune.GetRuneAt("\U0001D2E9", 0), System.Text.Rune.GetRuneAt("\U0001D2EA", 0), System.Text.Rune.GetRuneAt("\U0001D2EB", 0), System.Text.Rune.GetRuneAt("\U0001D2EC", 0), System.Text.Rune.GetRuneAt("\U0001D2ED", 0), System.Text.Rune.GetRuneAt("\U0001D2EE", 0), System.Text.Rune.GetRuneAt("\U0001D2EF", 0), System.Text.Rune.GetRuneAt("\U0001D2F0", 0), System.Text.Rune.GetRuneAt("\U0001D2F1", 0), System.Text.Rune.GetRuneAt("\U0001D2F2", 0), System.Text.Rune.GetRuneAt("\U0001D2F3", 0) };

//		/// <summary>Base 95 (https://en.wikipedia.org/wiki/ASCII)</summary>
//		public static System.ReadOnlySpan<System.Text.Rune> PrintableAscii
//			=> new System.Text.Rune[] { (System.Text.Rune)' ', (System.Text.Rune)'!', (System.Text.Rune)'\'', (System.Text.Rune)'#', (System.Text.Rune)'$', (System.Text.Rune)'%', (System.Text.Rune)'&', (System.Text.Rune)'\'', (System.Text.Rune)'(', (System.Text.Rune)')', (System.Text.Rune)'*', (System.Text.Rune)'+', (System.Text.Rune)',', (System.Text.Rune)'-', (System.Text.Rune)'.', (System.Text.Rune)'/', (System.Text.Rune)'0', (System.Text.Rune)'1', (System.Text.Rune)'2', (System.Text.Rune)'3', (System.Text.Rune)'4', (System.Text.Rune)'5', (System.Text.Rune)'6', (System.Text.Rune)'7', (System.Text.Rune)'8', (System.Text.Rune)'9', (System.Text.Rune)':', (System.Text.Rune)';', (System.Text.Rune)'<', (System.Text.Rune)'=', (System.Text.Rune)'>', (System.Text.Rune)'?', (System.Text.Rune)'@', (System.Text.Rune)'A', (System.Text.Rune)'B', (System.Text.Rune)'C', (System.Text.Rune)'D', (System.Text.Rune)'E', (System.Text.Rune)'F', (System.Text.Rune)'G', (System.Text.Rune)'H', (System.Text.Rune)'I', (System.Text.Rune)'J', (System.Text.Rune)'K', (System.Text.Rune)'L', (System.Text.Rune)'M', (System.Text.Rune)'N', (System.Text.Rune)'O', (System.Text.Rune)'P', (System.Text.Rune)'Q', (System.Text.Rune)'R', (System.Text.Rune)'S', (System.Text.Rune)'T', (System.Text.Rune)'U', (System.Text.Rune)'V', (System.Text.Rune)'W', (System.Text.Rune)'X', (System.Text.Rune)'Y', (System.Text.Rune)'Z', (System.Text.Rune)'[', (System.Text.Rune)'\\', (System.Text.Rune)']', (System.Text.Rune)'^', (System.Text.Rune)'_', (System.Text.Rune)'`', (System.Text.Rune)'a', (System.Text.Rune)'b', (System.Text.Rune)'c', (System.Text.Rune)'d', (System.Text.Rune)'e', (System.Text.Rune)'f', (System.Text.Rune)'g', (System.Text.Rune)'h', (System.Text.Rune)'i', (System.Text.Rune)'j', (System.Text.Rune)'k', (System.Text.Rune)'l', (System.Text.Rune)'m', (System.Text.Rune)'n', (System.Text.Rune)'o', (System.Text.Rune)'p', (System.Text.Rune)'q', (System.Text.Rune)'r', (System.Text.Rune)'s', (System.Text.Rune)'t', (System.Text.Rune)'u', (System.Text.Rune)'v', (System.Text.Rune)'w', (System.Text.Rune)'x', (System.Text.Rune)'y', (System.Text.Rune)'z', (System.Text.Rune)'{', (System.Text.Rune)'|', (System.Text.Rune)'}', (System.Text.Rune)'~' };
//	}
//}
